steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.fastapi', '-t', 'us-central1-docker.pkg.dev/gen-lang-client-0519489172/cloud-run-source-deploy/lars-engine', '.']
images:
  - 'us-central1-docker.pkg.dev/gen-lang-client-0519489172/cloud-run-source-deploy/lars-engine'
